# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

default_stages: [commit]
fail_fast: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            exclude: mkdocs.yaml
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.13.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            args: [--print-width=88, --tab-width=4]

    - repo: local
      hooks:
          - id: ruff-format
            name: ruff-format
            description: Ruff Format
            entry: uv run --only-dev ruff format
            language: system
            types:
                - file
            files: \.(py|ipynb)$
            require_serial: true
          - id: ruff-fix
            name: ruff-fix
            description: Ruff Check with Fix
            entry: uv run --only-dev ruff check --fix
            types:
                - file
            language: system
            files: \.(py|ipynb)$
            require_serial: true
