# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: uv-monorepo
docs_dir: ../docs
nav:
    - Home 🏠: index.md
    - uv ⚡️: uv.md
    - Taskfile 📝: taskfile.md
theme:
    favicon: https://juftin.com/favicon.ico
    logo: https://raw.githubusercontent.com/juftin/juftin/main/static/juftin.png
    name: material
    features:
        - navigation.tracking
        - content.code.annotate
        - content.code.copy
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: purple
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to light mode
repo_url: https://github.com/juftin/uv-monorepo
repo_name: uv-monorepo
edit_uri: blob/main/docs/
site_author: juftin
extra:
    generator: false
markdown_extensions:
    - toc:
          permalink: "#"
    - pymdownx.snippets:
          base_path:
              - !relative $config_dir
    - pymdownx.magiclink
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - markdown.extensions.attr_list
    - pymdownx.keys
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.tabbed:
          alternate_style: true
    - callouts
plugins:
    - search
    - markdown-exec
