[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
  "pydantic>=2.9.2"
]
dynamic = ["version"]
name = "package-a"
requires-python = ">=3.11,<4"

[tool.hatch.version]
path = "package_a/__init__.py"

[tool.uv]
dev-dependencies = [
  "hatch>=1.12.0",
  "pytest>=8.3.3",
  "coverage>=7.6.1",
  "mypy>=1.11.2"
]
