# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint
on:
    push:
        branches: [main]
        paths:
            - src/packages/**
            - src/services/**
            - .github/workflows/lint.yaml
    pull_request:
        branches:
            - main
        paths:
            - src/packages/**
            - src/services/**
            - .github/workflows/tests.yaml
env:
    PYTHON_VERSION: "3.12"
jobs:
    changed-files:
        name: changed-files
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
            changed: ${{ steps.changed-files.outputs.any_modified }}
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v45
              with:
                  matrix: true
                  dir_names: true
                  dir_names_max_depth: 3
                  files: |
                      src/packages/**
                      src/services/**
            - name: List all changed files
              run: echo "${{ toJSON(steps.changed-files.outputs) }}"
    lint:
        name: lint
        if: ${{ needs.changed-files.outputs.changed == 'true' }}
        needs:
            - changed-files
        strategy:
            fail-fast: false
            matrix:
                directories: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
        env:
            DIR: ${{ matrix.directories }}
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install uv
              uses: astral-sh/setup-uv@v2
            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                  version: 3.x
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Dependencies
              run: task install -- --only-dev
              env:
                  DIR: ${{ github.workspace }}
                  PRE_COMMIT: 0
            - name: Run Code Formatting
              run: task lint:format -- --diff
            - name: Run Code Linting
              run: task lint:check -- --output-format github
            - name: Install Dependencies for Type Checking
              run: task install
              env:
                  PRE_COMMIT: 0
            - name: Run Code Type Checking
              run: task lint:typing
